openapi: "3.0.1"
info:
   title: "users-api"
   description: "Users API"
   version: "1.0"

paths:

    /users:
        post:
            produces:
            - "application/json"
            summary: Add a User
            description: Add a User
            operationId: addUser
            x-amazon-apigateway-integration:
                httpMethod: "POST"
                credentials:
                    Fn::Sub: ${LambdaExecutionRole.Arn}
                uri: 
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                type: "aws_proxy"
                
        get:
            produces:
            - "application/json"
            summary: Get Users
            description: Get Users
            operationId: getUsers
            x-amazon-apigateway-integration:
                httpMethod: "POST"
                credentials:
                    Fn::Sub: ${LambdaExecutionRole.Arn}
                uri: 
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                type: "aws_proxy"
