openapi: 3.0.0
info:
  title: Support User Created Webhook API
  description: API for handling support user created webhook events
  version: 1.0.0

paths:
  /zendesk/webhooks/support-user-created:
    post:
      operationId: "CreatePet"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewPet"
        # required: true
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewPetResponse"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SupportUserCreatedFunction.Arn}/invocations
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'POST,GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
 
components:
  schemas:
    Pets:
      type: "array"
      items:
        $ref: "#/components/schemas/Pet"
    Empty:
      type: "object"
    NewPetResponse:
      type: "object"
      properties:
        pet:
          $ref: "#/components/schemas/Pet"
        message:
          type: "string"
    Pet:
      type: "object"
      properties:
        id:
          type: "integer"
        type:
          type: "string"
        price:
          type: "number"
    NewPet:
      type: "object"
      properties:
        type:
          $ref: "#/components/schemas/PetType"
        price:
          type: "number"
    PetType:
      type: "string"
      enum:
      - "dog"
      - "cat"
      - "fish"
      - "bird"
      - "gecko"
