AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for users API with IaC

Globals:
    # Enable Logs
    Api:
        MethodSettings:
            - ResourcePath: "/*"
              HttpMethod: "*"
              DataTraceEnabled: True
              LoggingLevel: INFO
              MetricsEnabled: True
    Function:
        Timeout: 900
        MemorySize: 2048
        Runtime: go1.x
        

Resources:

    # REST API                                                             
    UserAPI:
        Type: AWS::Serverless::Api
        DependsOn: ApiCWLRoleArn
        Properties:
            StageName: dev
            OpenApiVersion: 3.0.1
            DefinitionBody: # an OpenApi definition
                "Fn::Transform":
                    Name: "AWS::Include"
                    Parameters:
                        Location: "open-api.yaml"
            EndpointConfiguration:
                Type: REGIONAL

    ApiCWLRoleArn:
      Type: AWS::ApiGateway::Account
      Properties: 
        CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

    # IAM Role for API Gateway + CloudWatch Logging
    CloudWatchRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action: 'sts:AssumeRole'
              Effect: Allow
              Principal:
                Service: apigateway.amazonaws.com
          Path: /
          ManagedPolicyArns:
            - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'


    # Lambda functions                                                    
    UserFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: .
        Handler: userApi
        Architectures:
        - x86_64
      Metadata:
        BuildMethod: makefile
        Events:
          AddUser:
            Type: Api
            Properties:
              RestApiId: !Ref UserAPI
              Path: /users
              Method: post
          GetUsers:
            Type: Api
            Properties:
              RestApiId: !Ref UserAPI
              Path: /users
              Method: get
        
            
    # Execution Role
    LambdaExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Principal:
                      Service:
                        - apigateway.amazonaws.com
                    Action:
                      - 'sts:AssumeRole'
            Policies:
                - PolicyName: AllowLambdaExec
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                      - Effect: Allow
                        Action: 'lambda:InvokeFunction'
                        Resource: !GetAtt UserFunction.Arn
Outputs:
  UserAPI:
    Description: "API Gateway endpoint URL to call my first api"
    Value: !Sub "https://${UserAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/"
