# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go


name: lambda deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
        APP_ENV: 'dev'
        STACK_NAME: 'user-api'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: download dependencies
      run: go mod tidy -go=1.20

    - name: Build app with SAM
      run: sam build

    - name: Package
      run: |
        sam package --template-file .aws-sam/build/template.yaml \
        --s3-bucket ${{ secrets.S3_BUCKET }} \
        --output-template-file packaged.yaml 

    - name: Deploy
      run: |
        sam deploy --template-file packaged.yaml \
        --parameter-overrides \
            Stage=${{ env.APP_ENV }} \
        --stack-name ${{ env.STACK_NAME }}-${{ env.APP_ENV }} \
        --capabilities CAPABILITY_IAM \
        --no-confirm-changeset

